workspace:
  base: /usr/local/src/
  path: github.com/qnib/qcollect-ng
pipeline:
  build:
    image: qnib/uplain-golang
    commands:
     - govendor update +l
     - govendor fetch +m
     - govendor update +v
     - ./bin/test.sh
     - ./bin/build.sh
     - ./bin/release.sh
