workspace:
  base: /usr/local/src/
  path: github.com/qnib/qcollect-ng
pipeline:
  build:
    image: qnib/uplain-golang
    commands:
     - govendor update +l
     - govendor fetch +v
     - ./test.sh
     - ./build.sh
     - go build -o bin/qcollect-ng
